CREATE TABLE EMPLEADO1 (
  CI        INT         NOT NULL,
  F_NAC     DATE        NOT NULL,
  NOMBRES   VARCHAR(30) NOT NULL,
  APELLIDOS VARCHAR(30) NOT NULL,
  GENERO    VARCHAR(1)  NOT NULL,
  F_INICIO  DATE        NOT NULL,
  TIPO      VARCHAR(10) NOT NULL,
  PRIMARY KEY (CI)
);

CREATE TABLE DEPARTAMENTO (
  NUMERO INT         NOT NULL,
  NOMBRE VARCHAR(30) NOT NULL,
  PRIMARY KEY(NUMERO)
);

CREATE TABLE CONTRATO (
  NRO_CONTRATO SERIAL NOT NULL,
  INICIO       DATE   NOT NULL,
  FIN          DATE   NOT NULL,
  SUELDO       INT    NOT NULL,
  PRIMARY KEY (NRO_CONTRATO)
);

CREATE TABLE EMPLEADO2 (
  CI              INT         NOT NULL,
  USUARIO_TWITTER VARCHAR(15) NOT NULL UNIQUE,
  PRIMARY KEY(CI)
);

CREATE TABLE EMPLEADO (
  CI              INT         NOT NULL,
  F_NAC           DATE        NOT NULL,
  NOMBRES         VARCHAR(30) NOT NULL,
  APELLIDOS       VARCHAR(30) NOT NULL,
  GENERO          VARCHAR(1)  NOT NULL,
  F_INICIO        DATE        NOT NULL,
  TIPO            VARCHAR(10) NOT NULL,
  USUARIO_TWITTER VARCHAR(15) NOT NULL UNIQUE,
  PRIMARY KEY (CI)
);

CREATE TABLE TRABAJA (
  CI           INT      NOT NULL REFERENCES EMPLEADO(CI),
  NUMERO       INT      NOT NULL REFERENCES DEPARTAMENTO(NUMERO),
  NRO_CONTRATO SERIAL   NOT NULL REFERENCES CONTRATO(NRO_CONTRATO)
);

-- Agregar constraints

--EMPLEADO1

ALTER TABLE EMPLEADO1 ADD CONSTRAINT genero_dominio
  CHECK (GENERO = 'M' OR GENERO = 'F');

ALTER TABLE EMPLEADO1 ADD CONSTRAINT tipo_dominio
  CHECK (TIPO = 'empleado' OR TIPO = 'gerente');

ALTER TABLE EMPLEADO1 ADD CONSTRAINT fecha_nac_menor_inicio
  CHECK (F_INICIO > F_NAC);

--EMPLEADO

ALTER TABLE EMPLEADO ADD CONSTRAINT genero_dominio
  CHECK (GENERO = 'M' OR GENERO = 'F');

ALTER TABLE EMPLEADO ADD CONSTRAINT tipo_dominio
  CHECK (TIPO = 'empleado' OR TIPO = 'gerente');

--CONTRATO

ALTER TABLE CONTRATO ADD CONSTRAINT fecha_fin_mayor_fecha_inicio
  CHECK (FIN > INICIO);

